### ISSUE TITLE
Tests to check goroutines leak

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#269]
We can use https://github.com/uber-go/goleak at the beginning of each tendermint tests.

**Comment by JekaMas** [comment]
```
    --- PASS: TestTendermintStopUpToFNodes/test_case_F_nodes_stop_at_block_5 (21.00s)
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc00161e4e0, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 34240 in state select, with github.com/clearmatics/autonity/accounts.(*Manager).update on top of the stack:
        goroutine 34240 [select]:
        github.com/clearmatics/autonity/accounts.(*Manager).update(0xc0247c70a0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:110 +0x19c
        created by github.com/clearmatics/autonity/accounts.NewManager
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:78 +0x4c3
        
         Goroutine 34323 in state select, with github.com/clearmatics/autonity/accounts.(*Manager).update on top of the stack:
        goroutine 34323 [select]:
        github.com/clearmatics/autonity/accounts.(*Manager).update(0xc0247c7180)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:110 +0x19c
        created by github.com/clearmatics/autonity/accounts.NewManager
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:78 +0x4c3
        
         Goroutine 53645 in state select, with github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain on top of the stack:
        goroutine 53645 [select]:
        github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000f89040)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:110 +0x1b1
        created by github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x431
        
         Goroutine 53914 in state select, with github.com/clearmatics/autonity/miner.(*worker).newWorkLoop on top of the stack:
        goroutine 53914 [select]:
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc00161f1e0, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 54108 in state select, with github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain on top of the stack:
        goroutine 54108 [select]:
        github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00052e680)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:110 +0x1b1
        created by github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x431
        
         Goroutine 53655 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop on top of the stack:
        goroutine 53655 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop(0xc05eddf120)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:94 +0x4c6
        created by github.com/clearmatics/autonity/accounts/keystore.(*watcher).start
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:52 +0x59
        
         Goroutine 53606 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 53606 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0xdf8475800)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/core/rawdb.(*freezer).freeze(0xc07f0922c0, 0x1124e60, 0xc00056c300)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/freezer.go:262 +0x163
        created by github.com/clearmatics/autonity/core/rawdb.NewDatabaseWithFreezer
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/database.go:176 +0x200
        
         Goroutine 34283 in state select, with github.com/clearmatics/autonity/miner.(*worker).newWorkLoop on top of the stack:
        goroutine 34283 [select]:
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc000f88d00, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 34284 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 34284 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc000f88d00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 34724 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 34724 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc05c130370)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 54198 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 54198 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc05d3834f0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 53656 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater on top of the stack:
        goroutine 53656 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater(0xc0030d8780)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:205 +0xcd
        created by github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).Subscribe
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:192 +0x120
        
         Goroutine 34517 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 34517 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc00043f6c0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 53579 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop on top of the stack:
        goroutine 53579 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop(0xc05edded40)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:94 +0x4c6
        created by github.com/clearmatics/autonity/accounts/keystore.(*watcher).start
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:52 +0x59
        
         Goroutine 53827 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 53827 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc00185e680)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 53915 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 53915 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc00161f1e0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 53715 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 53715 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0xdf8475800)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/core/rawdb.(*freezer).freeze(0xc07f0762c0, 0x1124e60, 0xc0003a8240)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/freezer.go:262 +0x163
        created by github.com/clearmatics/autonity/core/rawdb.NewDatabaseWithFreezer
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/database.go:176 +0x200
        
         Goroutine 53701 in state select, with github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain on top of the stack:
        goroutine 53701 [select]:
        github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00161f040)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:110 +0x1b1
        created by github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x431
        
         Goroutine 34884 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 34884 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc05c1309b0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 35059 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 35059 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc002d1d4f0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 54415 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 54415 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc00345d310)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 53653 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater on top of the stack:
        goroutine 53653 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater(0xc0030d8690)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:205 +0xcd
        created by github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).Subscribe
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:192 +0x120
        
         Goroutine 34516 in state select, with github.com/clearmatics/autonity/miner.(*worker).newWorkLoop on top of the stack:
        goroutine 34516 [select]:
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc00043f6c0, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 34406 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 34406 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x8262982cf)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05bc943b0, 0xc00012fb80, 0xc05876f0e0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 34397 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 34397 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0xdf8475800)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/core/rawdb.(*freezer).freeze(0xc05d6d00a0, 0x1124e60, 0xc0002f6180)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/freezer.go:262 +0x163
        created by github.com/clearmatics/autonity/core/rawdb.NewDatabaseWithFreezer
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/database.go:176 +0x200
        
         Goroutine 53778 in state select, with github.com/clearmatics/autonity/miner.(*worker).newWorkLoop on top of the stack:
        goroutine 53778 [select]:
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc001cd24e0, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 53874 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 53874 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0xdf8475800)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/core/rawdb.(*freezer).freeze(0xc07ecc6b20, 0x1124e60, 0xc0000dc480)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/freezer.go:262 +0x163
        created by github.com/clearmatics/autonity/core/rawdb.NewDatabaseWithFreezer
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/database.go:176 +0x200
        
         Goroutine 53943 in state select, with github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain on top of the stack:
        goroutine 53943 [select]:
        github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc07956e000)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:110 +0x1b1
        created by github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb.openDB
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/vendor/github.com/syndtr/goleveldb/leveldb/db.go:143 +0x431
        
         Goroutine 34725 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 34725 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x825a9c976)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05bc94ab8, 0xc05cfbcdc0, 0xc05889f1a0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 34382 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 34382 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc00161eb60)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 53968 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 53968 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x82568b18f)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05e1b31f0, 0xc000373b80, 0xc0818eb020)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 53576 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop on top of the stack:
        goroutine 53576 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*watcher).loop(0xc05eddec60)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:94 +0x4c6
        created by github.com/clearmatics/autonity/accounts/keystore.(*watcher).start
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/watch.go:52 +0x59
        
         Goroutine 53580 in state select, with github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater on top of the stack:
        goroutine 53580 [select]:
        github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).updater(0xc0030d83c0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:205 +0xcd
        created by github.com/clearmatics/autonity/accounts/keystore.(*KeyStore).Subscribe
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/keystore/keystore.go:192 +0x120
        
         Goroutine 53779 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 53779 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc001cd24e0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 35080 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 35080 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x824ddcaa8)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05bc95aa8, 0xc000373340, 0xc0030de180)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 54229 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 54229 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x8259be3e5)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05e1b3360, 0xc059e3e840, 0xc058e8b080)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 35114 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 35114 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x8246588e4)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05acfb170, 0xc000311340, 0xc05889fc20)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 35193 in state chan receive, with github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop on top of the stack:
        goroutine 35193 [chan receive]:
        github.com/clearmatics/autonity/eth/filters.(*PublicFilterAPI).timeoutLoop(0xc002d1dd10)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:83 +0x122
        created by github.com/clearmatics/autonity/eth/filters.NewPublicFilterAPI
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/eth/filters/api.go:73 +0x149
        
         Goroutine 53780 in state select, with github.com/clearmatics/autonity/miner.(*worker).taskLoop on top of the stack:
        goroutine 53780 [select]:
        github.com/clearmatics/autonity/miner.(*worker).taskLoop(0xc001cd24e0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:532 +0xf2
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:220 +0x572
        
         Goroutine 53905 in state select, with github.com/clearmatics/autonity/miner.(*worker).resultLoop on top of the stack:
        goroutine 53905 [select]:
        github.com/clearmatics/autonity/miner.(*worker).resultLoop(0xc00043fba0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:568 +0xdd
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:219 +0x550
        
         Goroutine 53859 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 53859 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0xdf8475800)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/core/rawdb.(*freezer).freeze(0xc07f0a2380, 0x1124e60, 0xc00078a3c0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/freezer.go:262 +0x163
        created by github.com/clearmatics/autonity/core/rawdb.NewDatabaseWithFreezer
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/core/rawdb/database.go:176 +0x200
        
         Goroutine 54031 in state sleep, with runtime.goparkunlock on top of the stack:
        goroutine 54031 [sleep]:
        runtime.goparkunlock(...)
        	/snap/go/current/src/runtime/proc.go:307
        time.Sleep(0x82525720b)
        	/snap/go/current/src/runtime/time.go:105 +0x159
        github.com/clearmatics/autonity/p2p.waitExpireTask.Do(...)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/dial.go:374
        github.com/clearmatics/autonity/p2p.(*Server).run.func2.1(0x10feea0, 0xc05e61f5d0, 0xc05cfbd600, 0xc024a4afc0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x3b
        created by github.com/clearmatics/autonity/p2p.(*Server).run.func2
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/p2p/server.go:719 +0x1a8
        
         Goroutine 53651 in state select, with github.com/clearmatics/autonity/accounts.(*Manager).update on top of the stack:
        goroutine 53651 [select]:
        github.com/clearmatics/autonity/accounts.(*Manager).update(0xc0603382a0)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:110 +0x19c
        created by github.com/clearmatics/autonity/accounts.NewManager
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/accounts/manager.go:78 +0x4c3
        
         Goroutine 53773 in state select, with github.com/clearmatics/autonity/miner.(*worker).newWorkLoop on top of the stack:
        goroutine 53773 [select]:
        github.com/clearmatics/autonity/miner.(*worker).newWorkLoop(0xc000f891e0, 0x3b9aca00)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:355 +0x283
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:218 +0x52e
        
         Goroutine 53828 in state select, with github.com/clearmatics/autonity/miner.(*worker).taskLoop on top of the stack:
        goroutine 53828 [select]:
        github.com/clearmatics/autonity/miner.(*worker).taskLoop(0xc00185e680)
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:532 +0xf2
        created by github.com/clearmatics/autonity/miner.newWorker
        	/mnt/sdb/go/src/github.com/clearmatics/autonity/miner/worker.go:220 +0x572
        ]
```

**Comment by JekaMas** [comment]
fix 1 https://github.com/clearmatics/autonity/pull/302

**Comment by JekaMas** [comment]
fix 2 https://github.com/clearmatics/autonity/pull/305
