### ISSUE TITLE
Nil pointer error on TestTendermintStartStopAllNodes()

### ISSUE THREAD

**Issue by aneequesafdar** [clearmatics/autonity#307]
# Problem
```
=== RUN   TestTendermintStartStopAllNodes/test_case_all_nodes_stop_for_60_seconds_at_the_same_block
[31mERROR[0m[10-02|15:03:24.471] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:24.577] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:24.722] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:24.748] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.358] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.545] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:03:25.546] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:03:25.547] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:03:25.548] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:03:25.549] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:03:25.595] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.597] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.600] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.600] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:25.611] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.167] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.170] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.171] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.172] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.201] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.744] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.746] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.747] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:03:30.750] Deployed Autonity Contract               [31mAddress[0m=0xc3d854209eF19803954916F2fe4712448094363e
[31mERROR[0m[10-02|15:04:42.496] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:04:42.572] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:04:42.634] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:04:42.734] mining                                   [31mn[0m=1
[31mERROR[0m[10-02|15:05:33.251] test error!!!                            [31merr[0m="a validator 1 still have transactions to be mined 1. block 25. Total sent 9, total mined 8"
[31mERROR[0m[10-02|15:05:33.292] test error!!!                            [31merr[0m="a validator 0 still have transactions to be mined 2. block 25. Total sent 9, total mined 7"
[31mERROR[0m[10-02|15:05:33.294] test error!!!                            [31merr[0m="a validator 4 still have transactions to be mined 1. block 25. Total sent 9, total mined 8"
[31mERROR[0m[10-02|15:05:33.299] test error!!!                            [31merr[0m="a validator 2 still have transactions to be mined 1. block 25. Total sent 9, total mined 8"
[31mERROR[0m[10-02|15:05:33.868] mining                                   [31mn[0m=1
Transactions per block
Block 1 has 0 transactions
Block 2 has 4 transactions
Block 4 has 0 transactions
Block 5 has 2 transactions
Block 6 has 3 transactions
Block 7 has 4 transactions
Block 8 has 7 transactions
Block 9 has 3 transactions
Block 10 has 2 transactions
Block 11 has 4 transactions
Block 12 has 3 transactions
Block 13 has 0 transactions
Block 14 has 0 transactions
Block 15 has 0 transactions
Block 16 has 0 transactions
Block 17 has 0 transactions
Block 18 has 0 transactions
Block 19 has 0 transactions
Block 20 has 1 transactions
Block 21 has 0 transactions
Block 22 has 0 transactions
Block 23 has 0 transactions
Block 24 has 0 transactions
Block 25 has 0 transactions

Pending transactions
Validator 0 has 2 transactions
Validator 1 has 1 transactions
Validator 2 has 1 transactions
Validator 3 has 6 transactions
Validator 4 has 1 transactions
[31mERROR[0m[10-02|15:06:33.904] Error Autonity Contract callPerformRedistribution() [31merr[0m=nil
[31mERROR[0m[10-02|15:06:33.904] ApplyPerformRedistribution               [31merr[0m="evm: execution reverted"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xedacdd]

goroutine 1051705 [running]:
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).getProposer(...)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:139
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).IsProposer(0xc03b61b4f0, 0xefd335639bd986ca, 0x4e0c2712321c28ad, 0xe3337767, 0x0)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:147 +0x10d
github.com/clearmatics/autonity/consensus/tendermint/core.(*validatorSet).IsProposer(0xc0523ce480, 0xefd335639bd986ca, 0x4e0c2712321c28ad, 0xc0e3337767, 0x0)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/validator_set.go:109 +0xde
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).isProposer(...)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:216
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).startRound(0xc053aabb80, 0x1692dc0, 0xc04787db00, 0xc000108260)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:261 +0x3fc
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleConsensusEvents(0xc053aabb80, 0x1692dc0, 0xc04787db00)
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/handler.go:154 +0x8a
created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
	/home/clearmatics/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/handler.go:66 +0x829
FAIL	github.com/clearmatics/autonity/consensus/test	5073.253s
```

**Comment by yazzaoui** [comment]
Closing this issue
