### ISSUE TITLE
Private network panic

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#312]
```
{
 insertId: "hzy8z85nfby5vokr6"  
 labels: {…}  
 logName: "projects/platformx-3816/logs/stderr"  
 receiveTimestamp: "2019-10-10T15:26:12.033785014Z"  
 resource: {…}  
 severity: "ERROR"  
 textPayload: "panic: ([]error) (0xf70ca0,0xc019928aa0)
​
goroutine 1 [running]:
github.com/clearmatics/autonity/core/types.NewNodes(0xc0000aef30, 0x7, 0x9, 0xc01958cc00, 0x0)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/types/nodes.go:63 +0x554
github.com/clearmatics/autonity/core/rawdb.ReadEnodeWhitelist(0x7f195546ee90, 0xc0006202c0, 0xc000620200, 0x7f195546ee90)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/rawdb/accessors_chain.go:84 +0x26b
github.com/clearmatics/autonity/eth.NewProtocolManager(0xc000374460, 0x0, 0x0, 0x6c9d8, 0xc00028b230, 0x1407400, 0xc00000c1e0, 0x141f5a0, 0xc000634140, 0xc019584000, ...)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/eth/handler.go:210 +0x69c
github.com/clearmatics/autonity/eth.New(0xc0001ac660, 0xc000138000, 0x0, 0x10f1040, 0xc0006578f8, 0x423a58)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/eth/backend.go:246 +0xdf0
github.com/clearmatics/autonity/cmd/utils.RegisterEthService.func2(0xc0001ac660, 0xc00028bcb0, 0xc000657a70, 0xc0001ac620, 0x2)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/cmd/utils/flags.go:1503 +0x46
github.com/clearmatics/autonity/node.(*Node).Start(0xc000615680, 0x0, 0x0)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/node/node.go:206 +0x400
github.com/clearmatics/autonity/cmd/utils.StartNode(0xc000615680)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc0004ae160, 0xc000615680)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/cmd/autonity/main.go:312 +0x73
main.autonity(0xc0004ae160, 0x0, 0x0)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/cmd/autonity/main.go:300 +0x16f
github.com/clearmatics/autonity/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xfa64c0, 0x1224cb0, 0xc0004ae160, 0xc0004ae160, 0xc000657f58)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/clearmatics/autonity/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000494ea0, 0xc000032240, 0x23, 0x24, 0x0, 0x0)
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x590
main.main()
	/autonity/build/_workspace/src/github.com/clearmatics/autonity/cmd/autonity/main.go:285 +0x55
"  
 timestamp: "2019-10-10T15:26:02.445709540Z"  
}
```

**Comment by yazzaoui** [comment]
Correct me if I'm wrong @JekaMas but right now the client panic if it fails to resolve only one hostname from the white list after max try = 300 right?  
I see 2 posible design options :
1. Remove max try, keep trying until 100% successful resolve.
2. Only return nodes that could be resolved after first try with a new flag to not start outgoing connection but only accept incoming. Continue to try resolving asynchronously failed resolves.

I guess maybe @eastata can give us his ideas as well.

**Comment by eastata** [comment]
Is `2` have sense? 
Definitely bootstrap process should not been limited by `max try`
