### ISSUE TITLE
Panic on stop

### ISSUE THREAD

**Issue by b00ris** [clearmatics/autonity#423]
# Problem
Panic on stop. On tests with changing topology. 
```
Boris, [18 Feb 2020 at 13:38:33]:
...NFO [02-17|14:07:29.165] Blockchain manager stopped 
INFO [02-17|14:07:29.165] Stopping Ethereum protocol 
INFO [02-17|14:07:29.165] Ethereum protocol stopped 
INFO [02-17|14:07:29.165] Transaction pool stopped 
INFO [02-17|14:07:29.163] Transaction pool stopped 
DEBUG[02-17|14:07:29.163] Removing p2p peer                        id=1c0533bb761db93b conn=trusted-inbound    addr=127.0.0.1:56304 peers=0 duration=36.516s            req=false err="client quitting"
TRACE[02-17|14:07:29.165] New dial task                            task="staticdial 1c0533bb761db93b 127.0.0.1:39824"
DEBUG[02-17|14:07:29.163] Removing p2p peer                        id=11f3a474c4ebae2a conn=trusted-staticdial addr=127.0.0.1:44649 peers=1 duration=36.517s            req=false err="client quitting"
TRACE[02-17|14:07:29.165] New dial task                            task="staticdial 11f3a474c4ebae2a 127.0.0.1:44649"
DEBUG[02-17|14:07:29.165] Removing p2p peer                        id=5c7c0a5ee3c8d58e conn=inbound            addr=127.0.0.1:32908 peers=0 duration=1.529s             req=false err="client quitting"
TRACE[02-17|14:07:29.165] Dial task done                           task="staticdial c6ec7c5b356631e3 127.0.0.1:43574"
TRACE[02-17|14:07:29.165] P2P networking is spinning down 
DEBUG[02-17|14:07:29.165] Reset ancient limit to zero 
TRACE[02-17|14:07:29.166] Dial error                               task="staticdial 1c0533bb761db93b 127.0.0.1:39824" err="dial tcp 127.0.0.1:39824: connect: connection refused"
DEBUG[02-17|14:07:29.166] Can't resolve node                       id=1c0533bb761db93b err="discovery is disabled"
TRACE[02-17|14:07:29.166] Dial task done                           task="staticdial 1c0533bb761db93b 127.0.0.1:39824"
TRACE[02-17|14:07:29.166] Dial error                               task="staticdial c6ec7c5b356631e3 127.0.0.1:43574" err="dial tcp 127.0.0.1:43574: connect: connection refused"
DEBUG[02-17|14:07:29.166] Can't resolve node                       id=c6ec7c5b356631e3 err="discovery is disabled"
DEBUG[02-17|14:07:29.166] Read error                               err="accept tcp 127.0.0.1:40858: use of closed network connection"
DEBUG[02-17|14:07:29.166] Read error                               err="accept tcp 127.0.0.1:44649: use of closed network connection"
INFO [02-17|14:07:29.166] cant stop timer                          addr=0xB3199F0230e0cfcD3fF2718bEcB31F4D09d3EB95 err="timer expired and nil prevote sent"
DEBUG[02-17|14:07:29.166] Starting new Round                       addr=0xB3199F0230e0cfcD3fF2718bEcB31F4D09d3EB95 Height=27 Round=0
TRACE[02-17|14:07:29.166] Rejected peer                            id=1c0533bb761db93b addr=127.0.0.1:39824 conn=staticdial         err="server stopped"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xce967f]

goroutine 46614 [running]:
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).getProposer(0xc0653e2cd0, 0xcdcfe030029f19b3, 0x4d1fb3ec8b71f23f)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:132 +0x3f
github.com/clearmatics/autonity/consensus/tendermint/validator.(*defaultSet).IsProposer(0xc0653e2cd0, 0xcdcfe030029f19b3, 0x4d1fb3ec8b71f23f, 0x95ebd309, 0xc0003ed300)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/validator/default.go:140 +0xd6
github.com/clearmatics/autonity/consensus/tendermint/core.(*validatorSet).IsProposer(0xc066c4fe90, 0xcdcfe030029f19b3, 0x4d1fb3ec8b71f23f, 0xc095ebd309, 0x0)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/validator_set.go:109 +0x9e
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).isProposer(...)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:223
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).startRound(0xc0002c7b80, 0x13247c0, 0xc064a19940, 0xc00000e200)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/core.go:286 +0x2d8
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleConsensusEvents(0xc0002c7b80, 0x13247c0, 0xc064a19940)
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/handler.go:160 +0x69
created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
  /home/b00ris/go/src/github.com/clearmatics/autonity/consensus/tendermint/core/handler.go:66 +0x349
```

# Acceptance Criteria
Panic is not reproduced

**Comment by JekaMas** [comment]
Closed by https://github.com/clearmatics/autonity/pull/447
