### ISSUE TITLE
Istanbul API `istanbul.getValidators()` failing

### ISSUE THREAD

**Issue by daragao** [clearmatics/autonity#47]
When doing `istanbul.getValidators()` after attaching a console, autonity breaks:

While using [helloworld](https://github.com/clearmatics/autonity/tree/hello_world/helloworld) (currently in hello_world branch)

```
ERROR[02-14|23:15:31.701] goroutine 184 [running]:
github.com/clearmatics/autonity/rpc.(*Server).serveRequest.func1(0xc00581f8c0, 0x1238760, 0xc00526b4a0)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/server.go:132 +0xf2
panic(0xe901c0, 0x1957ca0)
      /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/clearmatics/autonity/consensus/istanbul/backend.(*API).GetValidators(0xc0057aebe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/istanbul/backend/api.go:33 +0x43
reflect.Value.call(0xc0058035c0, 0xc00000f880, 0x13, 0xfcc9b5, 0x4, 0xc00596f140, 0x2, 0x2, 0x0, 0xc00596f140, ...)
      /usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0xc0058035c0, 0xc00000f880, 0x13, 0xc00596f140, 0x2, 0x2, 0x1, 0x1, 0x0)
      /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/clearmatics/autonity/rpc.(*Server).handle(0xc00581f8c0, 0x1232ea0, 0xc0059d6000, 0x1238760, 0xc00526b4a0, 0xc005954c60, 0xc00526b510, 0x0, 0xe82660)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/server.go:309 +0x6cc
github.com/clearmatics/autonity/rpc.(*Server).exec(0xc00581f8c0, 0x1232ea0, 0xc0059d6000, 0x1238760, 0xc00526b4a0, 0xc005954c60)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/server.go:330 +0x1a6
github.com/clearmatics/autonity/rpc.(*Server).serveRequest(0xc00581f8c0, 0x1232f60, 0xc00596f0b0, 0x1238760, 0xc00526b4a0, 0xfd5a01, 0x1, 0x0, 0x0)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/server.go:192 +0x36e
github.com/clearmatics/autonity/rpc.(*Server).ServeSingleRequest(0xc00581f8c0, 0x1232f60, 0xc00596f0b0, 0x1238760, 0xc00526b4a0, 0x1)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/server.go:223 +0x65
github.com/clearmatics/autonity/rpc.(*Server).ServeHTTP(0xc00581f8c0, 0x12317a0, 0xc005938700, 0xc000268a00)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/http.go:253 +0x4a6
github.com/clearmatics/autonity/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x12317a0, 0xc005938700, 0xc000268a00)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/vendor/github.com/rs/cors/cors.go:190 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc005848ee0, 0x12317a0, 0xc005938700, 0xc000268a00)
      /usr/local/go/src/net/http/server.go:1964 +0x44
github.com/clearmatics/autonity/rpc.(*virtualHostHandler).ServeHTTP(0xc005848f00, 0x12317a0, 0xc005938700, 0xc000268a00)
      /autonity/build/_workspace/src/github.com/clearmatics/autonity/rpc/http.go:311 +0x206
net/http.serverHandler.ServeHTTP(0xc005858000, 0x12317a0, 0xc005938700, 0xc000268a00)
      /usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc005978460, 0x1232ea0, 0xc0058976c0)
      /usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
      /usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by aesmonty** [comment]
@daragao Are you using the latest version? Seems to work fine for me

**Comment by aesmonty** [comment]
@yazzaoui It works fine, closing the issue.
