### ISSUE TITLE
[CI] restore tests and corresponding code

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#51]
#### Expected behaviour
Tests passed without `-race` flag

#### Actual behaviour
Tests fail and panic in a few places

#### Steps to reproduce the behaviour
`make test`

#### Backtrace

````
--- FAIL: TestBindings (1.44s)
    bind_test.go:976: failed to run binding test: exit status 1
        exit status 1
        FAIL	_/tmp/226062759/bindtest	0.058s
FAIL
FAIL	github.com/clearmatics/autonity/accounts/abi/bind	3.527s

--- FAIL: TestCompiler (0.10s)
    solidity_test.go:46: error compiling source. result map[]: solc: exit status 1
        <stdin>:4:4: Error: No visibility specified. Did you intend to add "public"?
           function multiply(uint a) returns(uint d) {
           ^ (Relevant source part starts here and spans across multiple lines).
        <stdin>:2:1: Warning: Source file does not specify required compiler version! Consider adding "pragma solidity ^0.5.2;"
        contract test {
        ^ (Relevant source part starts here and spans across multiple lines).
FAIL
FAIL	github.com/clearmatics/autonity/common/compiler	0.215s

--- FAIL: TestClique (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x87c061]

goroutine 28 [running]:
testing.tRunner.func1(0xc00017c400)
	/snap/go/3417/src/testing/testing.go:830 +0x392
panic(0x92fe60, 0x10571c0)
	/snap/go/3417/src/runtime/panic.go:522 +0x1b5
github.com/clearmatics/autonity/core.(*Genesis).Commit(0xc0001adee8, 0xac72a0, 0xc0001a3660, 0xc0000ae200, 0x6119dae23e876b5e, 0xd203fed3)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:284 +0x581
github.com/clearmatics/autonity/consensus/clique.TestClique(0xc00017c400)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/clique/snapshot_test.go:404 +0x216e
testing.tRunner(0xc00017c400, 0x9ec760)
	/snap/go/3417/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/snap/go/3417/src/testing/testing.go:916 +0x35a
FAIL	github.com/clearmatics/autonity/consensus/clique	0.022s

--- FAIL: TestVerifyHeaders (0.25s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8132f5]

goroutine 120 [running]:
testing.tRunner.func1(0xc06900c400)
	/snap/go/3417/src/testing/testing.go:830 +0x392
panic(0x94aae0, 0x10cf1d0)
	/snap/go/3417/src/runtime/panic.go:522 +0x1b5
github.com/clearmatics/autonity/core/state.(*StateDB).getStateObject(0x0, 0x3613, 0x0, 0x0, 0xc0863d2540)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/state/statedb.go:408 +0x85
github.com/clearmatics/autonity/core/state.(*StateDB).GetBalance(0x0, 0x3613, 0x0, 0x0, 0x0)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/state/statedb.go:208 +0x3f
github.com/clearmatics/autonity/core.CanTransfer(0xb36d20, 0x0, 0x3613, 0x0, 0x0, 0xc0863cee40, 0x20)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/evm.go:90 +0x45
github.com/clearmatics/autonity/core/vm.(*EVM).Call(0xc0863d4000, 0xb25600, 0xc0863bd960, 0x398f19e2054d8c3, 0x441247fef2164995, 0x3e369480, 0xc0863bd940, 0x4, 0x20, 0xffffffff, ...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/vm/evm.go:191 +0x13d
github.com/clearmatics/autonity/consensus/istanbul/backend.(*backend).contractGetValidators(0xc075b732c0, 0xb32100, 0xc08638a000, 0xc0863d0240, 0x0, 0x89f59a, 0xc08638a000, 0xeb01eb45b27f09b6, 0xc0863abc68, 0x810d83)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/istanbul/backend/contract.go:89 +0x37e
github.com/clearmatics/autonity/consensus/istanbul/backend.(*backend).Finalize(0xc075b732c0, 0xb32100, 0xc08638a000, 0xc0863d0240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/istanbul/backend/engine.go:370 +0x593
github.com/clearmatics/autonity/consensus/istanbul/backend.makeBlockWithoutSeal(0xc08638a000, 0xc075b732c0, 0xc0652a1440, 0x0)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/istanbul/backend/engine_test.go:142 +0x172
github.com/clearmatics/autonity/consensus/istanbul/backend.TestVerifyHeaders(0xc06900c400)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/consensus/istanbul/backend/engine_test.go:330 +0x159
testing.tRunner(0xc06900c400, 0xa51eb8)
	/snap/go/3417/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/snap/go/3417/src/testing/testing.go:916 +0x35a
FAIL	github.com/clearmatics/autonity/consensus/istanbul/backend	5.111s

exit status 1
FAIL	github.com/clearmatics/autonity/contracts/chequebook	0.051s
?   	github.com/clearmatics/autonity/contracts/chequebook/contract	[no test files]
exit status 1
FAIL	github.com/clearmatics/autonity/contracts/ens	0.039s
?   	github.com/clearmatics/autonity/contracts/ens/contract	[no test files]
# github.com/clearmatics/autonity/core
core/tx_pool_test.go:129:11: Errorf format %d has arg received of wrong type []*github.com/clearmatics/autonity/core/types.Transaction
FAIL	github.com/clearmatics/autonity/core [build failed]

# github.com/clearmatics/autonity/crypto/bn256/google
crypto/bn256/google/main_test.go:16:3: Logf format %d has arg n of wrong type *math/big.Int
FAIL	github.com/clearmatics/autonity/crypto/bn256/google [build failed]

# github.com/clearmatics/autonity/eth [github.com/clearmatics/autonity/eth.test]
eth/handler_test.go:481:31: not enough arguments in call to NewProtocolManager
	have (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, *testTxPool, *ethash.Ethash, *"github.com/clearmatics/autonity/core".BlockChain, *ethdb.MemDatabase, nil, Protocol)
	want (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, txPool, consensus.Engine, *"github.com/clearmatics/autonity/core".BlockChain, ethdb.Database, map[uint64]common.Hash, Protocol, bool)
eth/handler_test.go:562:31: not enough arguments in call to NewProtocolManager
	have (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, *testTxPool, *ethash.Ethash, *"github.com/clearmatics/autonity/core".BlockChain, *ethdb.MemDatabase, nil, Protocol)
	want (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, txPool, consensus.Engine, *"github.com/clearmatics/autonity/core".BlockChain, ethdb.Database, map[uint64]common.Hash, Protocol, bool)
eth/helper_test.go:69:31: not enough arguments in call to NewProtocolManager
	have (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, *testTxPool, *ethash.Ethash, *"github.com/clearmatics/autonity/core".BlockChain, *ethdb.MemDatabase, nil, Protocol)
	want (*params.ChainConfig, downloader.SyncMode, uint64, *event.TypeMux, txPool, consensus.Engine, *"github.com/clearmatics/autonity/core".BlockChain, ethdb.Database, map[uint64]common.Hash, Protocol, bool)
FAIL	github.com/clearmatics/autonity/eth [build failed]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x887361]

goroutine 1 [running]:
github.com/clearmatics/autonity/core.(*Genesis).Commit(0xc0001e5e70, 0xb24340, 0xc0001a5660, 0xc00012cfa8, 0x8, 0x20)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:284 +0x581
github.com/clearmatics/autonity/core.(*Genesis).MustCommit(...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:305
github.com/clearmatics/autonity/core.GenesisBlockForTesting(0xb24340, 0xc0001a5660, 0xdb739899712b5671, 0x9e19af57f96d285b, 0xdb739899f71746c9, 0xc0001a5680, 0xf71746c9)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:315 +0x147
github.com/clearmatics/autonity/eth/downloader.init.ializers()
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/eth/downloader/testchain_test.go:38 +0xb58
FAIL	github.com/clearmatics/autonity/eth/downloader	0.022s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x895161]

goroutine 1 [running]:
github.com/clearmatics/autonity/core.(*Genesis).Commit(0xc0001bbe50, 0xaee620, 0xc000177620, 0xc0000d6fa8, 0x8, 0xc000194a00)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:284 +0x581
github.com/clearmatics/autonity/core.(*Genesis).MustCommit(...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:305
github.com/clearmatics/autonity/core.GenesisBlockForTesting(0xaee620, 0xc000177620, 0xdb739899712b5671, 0x9e19af57f96d285b, 0xdb739899f71746c9, 0xc0001776a0, 0x9e0b05a7f71746c9)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:315 +0x147
github.com/clearmatics/autonity/eth/fetcher.init.ializers()
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/eth/fetcher/fetcher_test.go:40 +0x50c
FAIL	github.com/clearmatics/autonity/eth/fetcher	0.021s
--- FAIL: TestFilters (0.09s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x901eb1]

goroutine 67 [running]:
testing.tRunner.func1(0xc000111200)
	/snap/go/3417/src/testing/testing.go:830 +0x392
panic(0xabcda0, 0x138f580)
	/snap/go/3417/src/runtime/panic.go:522 +0x1b5
github.com/clearmatics/autonity/core.(*Genesis).Commit(0xc0000cdb90, 0xcc8e60, 0xc0000c9290, 0xc00013e6a8, 0x0, 0x20)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:284 +0x581
github.com/clearmatics/autonity/core.(*Genesis).MustCommit(...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:305
github.com/clearmatics/autonity/core.GenesisBlockForTesting(0xcc8e60, 0xc0000c9290, 0xdb739899712b5671, 0x9e19af57f96d285b, 0xdb739899f71746c9, 0xc00014c060, 0xf71746c9)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:315 +0x147
github.com/clearmatics/autonity/eth/filters.TestFilters(0xc000111200)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/eth/filters/filter_test.go:130 +0x533
testing.tRunner(0xc000111200, 0xbbcfa0)
	/snap/go/3417/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/snap/go/3417/src/testing/testing.go:916 +0x35a
FAIL	github.com/clearmatics/autonity/eth/filters	0.114s

FAIL	github.com/clearmatics/autonity/les	5.998s
?   	github.com/clearmatics/autonity/les/flowcontrol	[no test files]
--- FAIL: TestOdrGetBlockLes1 (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x887dd1]

goroutine 127 [running]:
testing.tRunner.func1(0xc00017c900)
	/snap/go/3417/src/testing/testing.go:830 +0x392
panic(0x967440, 0x10cc1f0)
	/snap/go/3417/src/runtime/panic.go:522 +0x1b5
github.com/clearmatics/autonity/core.(*Genesis).Commit(0xc000503ec0, 0xb0f020, 0xc0003ac820, 0xc0000f26a8, 0x0, 0x0)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:284 +0x581
github.com/clearmatics/autonity/core.(*Genesis).MustCommit(...)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/core/genesis.go:305
github.com/clearmatics/autonity/light.testChainOdr(0xc00017c900, 0x1, 0xa2b560)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/light/odr_test.go:256 +0x211
github.com/clearmatics/autonity/light.TestOdrGetBlockLes1(0xc00017c900)
	/mnt/sdb/go/src/github.com/clearmatics/autonity/build/_workspace/src/github.com/clearmatics/autonity/light/odr_test.go:102 +0x40
testing.tRunner(0xc00017c900, 0xa2b510)
	/snap/go/3417/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/snap/go/3417/src/testing/testing.go:916 +0x35a
FAIL	github.com/clearmatics/autonity/light	0.666s
util.go:45: exit status 2
exit status 1
Makefile:38: recipe for target 'test' failed
make: *** [test] Error 1
````

**Comment by JekaMas** [comment]
via https://github.com/clearmatics/autonity/pull/52
