### ISSUE TITLE
Fix TestTendermintMajorityExternalUsersFullyConnected

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#619]
# Problem

These tests are intermittently failing due to a goroutine leak.

They seem to pass on my machine but fail on CI.

 The below log extract was taken from the github [actions run for the `0.5.0` release](https://github.com/clearmatics/autonity/actions/runs/164686968) showing the failure of TestTendermintMajorityExternalUsersFullyConnected
```
2020-07-10T14:53:33.6621675Z [31mERROR[0m[07-10|14:53:33.661] Error stopping Consensus Engine          [31merror[0m="stopped engine"
2020-07-10T14:53:35.4459616Z --- FAIL: TestTendermintMajorityExternalUsersFullyConnected (154.45s)
2020-07-10T14:53:35.4460520Z     --- FAIL: TestTendermintMajorityExternalUsersFullyConnected/test_case_no_malicious (154.45s)
2020-07-10T14:53:35.4687517Z ##[error]        leaks.go:78: found unexpected goroutines:
2020-07-10T14:53:35.4718455Z             [Goroutine 6772 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleNewUnminedBlockEvent on top of the stack:
2020-07-10T14:53:35.4718685Z             goroutine 6772 [select]:
2020-07-10T14:53:35.4718984Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleNewUnminedBlockEvent(0xc000233e00, 0x13a3fa0, 0xc0f4da4300)
2020-07-10T14:53:35.4719270Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:101 +0xfd
2020-07-10T14:53:35.4719509Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
2020-07-10T14:53:35.4719740Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:43 +0x1e5
2020-07-10T14:53:35.4719873Z             
2020-07-10T14:53:35.4720165Z              Goroutine 6773 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop on top of the stack:
2020-07-10T14:53:35.4720338Z             goroutine 6773 [select]:
2020-07-10T14:53:35.4720770Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop(0xc000233e00, 0x13a3fa0, 0xc0f4da4300)
2020-07-10T14:53:35.4721000Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:126 +0x1fb
2020-07-10T14:53:35.4721416Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
2020-07-10T14:53:35.4722291Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:46 +0x224
2020-07-10T14:53:35.4722635Z             
2020-07-10T14:53:35.4722953Z              Goroutine 6775 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).syncLoop on top of the stack:
2020-07-10T14:53:35.4723141Z             goroutine 6775 [select]:
2020-07-10T14:53:35.4723429Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).syncLoop(0xc000233e00, 0x13a3fa0, 0xc0f4da4300)
2020-07-10T14:53:35.4723691Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:206 +0x1de
2020-07-10T14:53:35.4723961Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop
2020-07-10T14:53:35.4724218Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:122 +0xa5
2020-07-10T14:53:35.4724467Z             
2020-07-10T14:53:35.4724597Z             ]
2020-07-10T14:53:35.4724925Z FAIL
2020-07-10T14:53:35.6889536Z FAIL	github.com/clearmatics/autonity/consensus/test	154.721s
2020-07-10T14:53:35.7099982Z FAIL
2020-07-10T14:53:36.0476718Z ##[error]Process completed with exit code 1.
```

And this extract from another [ci run](https://github.com/clearmatics/autonity/pull/623/checks?check_run_id=893374616) shows the failure for TestTendermintMajorityExternalUsers
```
2020-07-21T08:37:38.3847321Z Transactions OK
2020-07-21T08:37:38.3904925Z [31mERROR[0m[07-21|08:37:38.390] Error stopping Consensus Engine          [31merror[0m="stopped engine"
2020-07-21T08:37:40.5841333Z --- FAIL: TestTendermintMajorityExternalUsers (184.91s)
2020-07-21T08:37:40.5841906Z     --- FAIL: TestTendermintMajorityExternalUsers/test_case_no_malicious (184.91s)
2020-07-21T08:37:40.5944226Z ##[error]        leaks.go:78: found unexpected goroutines:
2020-07-21T08:37:40.5987992Z             [Goroutine 4475 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop on top of the stack:
2020-07-21T08:37:40.5988271Z             goroutine 4475 [select]:
2020-07-21T08:37:40.5988713Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop(0xc00042ed80, 0x13a45c0, 0xc13309a040)
2020-07-21T08:37:40.5989067Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:126 +0x1fb
2020-07-21T08:37:40.5989385Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
2020-07-21T08:37:40.5989710Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:46 +0x224
2020-07-21T08:37:40.5989894Z             
2020-07-21T08:37:40.5990307Z              Goroutine 4474 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleNewUnminedBlockEvent on top of the stack:
2020-07-21T08:37:40.5990545Z             goroutine 4474 [select]:
2020-07-21T08:37:40.5990929Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).handleNewUnminedBlockEvent(0xc00042ed80, 0x13a45c0, 0xc13309a040)
2020-07-21T08:37:40.5991254Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:101 +0xfd
2020-07-21T08:37:40.5991867Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).Start
2020-07-21T08:37:40.5992241Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:43 +0x1e5
2020-07-21T08:37:40.5992422Z             
2020-07-21T08:37:40.5992946Z              Goroutine 4479 in state select, with github.com/clearmatics/autonity/consensus/tendermint/core.(*core).syncLoop on top of the stack:
2020-07-21T08:37:40.5993173Z             goroutine 4479 [select]:
2020-07-21T08:37:40.5993754Z             github.com/clearmatics/autonity/consensus/tendermint/core.(*core).syncLoop(0xc00042ed80, 0x13a45c0, 0xc13309a040)
2020-07-21T08:37:40.5994077Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:206 +0x1de
2020-07-21T08:37:40.5994406Z             created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop
2020-07-21T08:37:40.5994723Z             	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:122 +0xa5
2020-07-21T08:37:40.5994913Z             ]
```

# Acceptance Criteria

Given that there is no easy way to determine if these tests are really fixed (local runs pass and re-running github actions will be incredibly slow) the PR must make it clear that the currently leaking goroutines are being correctly shut down.

**Comment by yazzaoui** [comment]
closing it for the time being until this issue arise again.
