### ISSUE TITLE
Intermittent panic in TestTendermintStopUpToFNodes 

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#637]
# Problem
A panic occurred in the following githiub actions run. 
https://github.com/clearmatics/autonity/runs/949060195?check_suite_focus=true

An excerpt is below.

```
2020-08-05T11:43:00.0623028Z Block 10 has 6 transactions
2020-08-05T11:43:00.0623451Z Block 11 has 2 transactions
2020-08-05T11:43:00.0623762Z Block 12 has 4 transactions
2020-08-05T11:43:00.0624068Z Validator VB has 0 transactions
2020-08-05T11:43:00.0624368Z Validator VC has 0 transactions
2020-08-05T11:43:00.0624688Z Validator VD has 0 transactions
2020-08-05T11:43:00.0625029Z Validator VE has 0 transactions
2020-08-05T11:43:00.0625335Z Validator VA has 0 transactions
2020-08-05T11:43:00.0625551Z 
2020-08-05T11:43:00.0625961Z Transactions OK
2020-08-05T11:43:00.0780518Z panic: sync: WaitGroup is reused before previous Wait has returned
2020-08-05T11:43:00.0780874Z 
2020-08-05T11:43:00.0781148Z goroutine 10628 [running]:
2020-08-05T11:43:00.0781398Z sync.(*WaitGroup).Wait(0xc00032c428)
2020-08-05T11:43:00.0781696Z 	/opt/hostedtoolcache/go/1.13.14/x64/src/sync/waitgroup.go:132 +0xad
2020-08-05T11:43:00.0781992Z github.com/clearmatics/autonity/core.(*BlockChain).Stop(0xc00032c000)
2020-08-05T11:43:00.0782277Z 	/home/runner/work/autonity/autonity/core/blockchain.go:920 +0xa0
2020-08-05T11:43:00.0782591Z github.com/clearmatics/autonity/eth.(*Ethereum).Stop(0xc0178ab300, 0xc0002a5200, 0xc01242ade8)
2020-08-05T11:43:00.0782874Z 	/home/runner/work/autonity/autonity/eth/backend.go:631 +0xf8
2020-08-05T11:43:00.0783173Z github.com/clearmatics/autonity/node.(*Node).Stop(0xc071b40840, 0x0, 0x0)
2020-08-05T11:43:00.0783453Z 	/home/runner/work/autonity/autonity/node/node.go:490 +0x2fa
2020-08-05T11:43:00.0783750Z github.com/clearmatics/autonity/node.(*Node).Close(0xc071b40840, 0x10, 0xf702c0)
2020-08-05T11:43:00.0784032Z 	/home/runner/work/autonity/autonity/node/node.go:135 +0x40
2020-08-05T11:43:00.0784329Z github.com/clearmatics/autonity/consensus/test.runTest.func3.1(0xc00cc8bf68, 0x2)
2020-08-05T11:43:00.0784790Z 	/home/runner/work/autonity/autonity/consensus/test/testcase_test.go:252 +0x4a
2020-08-05T11:43:00.0785145Z golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0259b5ef0, 0xc025aa9f60)
2020-08-05T11:43:00.0785962Z 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
2020-08-05T11:43:00.0786337Z created by golang.org/x/sync/errgroup.(*Group).Go
2020-08-05T11:43:00.0786901Z 	/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
2020-08-05T11:43:00.0989536Z FAIL	github.com/clearmatics/autonity/consensus/test	37.084s
2020-08-05T11:43:00.1017351Z FAIL
```

# Acceptance Criteria
Since this happens intermittently, it will be hard to verify the fix therefore the PR should make it clear what the problem was and how it has been fixed.

**Comment by lorenzo-dev1** [comment]
Same as https://github.com/autonity/autonity/issues/624#issuecomment-2459029554

I think the new name for this test is `TestResetRandomFNodes`, is this correct @Jason-Zhangxin-Chen ?
