### ISSUE TITLE
TestTendermintStartStopFPlusOneNodes intermittent index out of range failure [RISKY/2D]

### ISSUE THREAD

**Issue by piersy** [clearmatics/autonity#646]
# Problem
The following failure occurred in the following CI run.
https://github.com/clearmatics/autonity/runs/973650539?check_suite_focus=true

```
panic: runtime error: index out of range [3] with length 2

goroutine 114706 [running]:
github.com/clearmatics/autonity/consensus/tendermint/core.(*messagesMap).GetMessages(0xc0196bce88, 0x0, 0x0, 0x0)
	/home/runner/work/autonity/autonity/consensus/tendermint/core/round_messages.go:65 +0x40c
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).GetCurrentHeightMessages(0xc0196bcd80, 0xc006f18bd0, 0xc001466e0c, 0xc0059e2d28)
	/home/runner/work/autonity/autonity/consensus/tendermint/core/core.go:166 +0x33
github.com/clearmatics/autonity/consensus/tendermint/backend.(*Backend).SyncPeer(0xc007216c80, 0xdbeedb5abf53be17, 0x5c16a185ad7718f9, 0xc0985711e2)
	/home/runner/work/autonity/autonity/consensus/tendermint/backend/backend.go:440 +0x218
github.com/clearmatics/autonity/consensus/tendermint/core.(*core).syncLoop(0xc0196bcd80, 0x1371260, 0xc00342c540)
	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:225 +0x347
created by github.com/clearmatics/autonity/consensus/tendermint/core.(*core).mainEventLoop
	/home/runner/work/autonity/autonity/consensus/tendermint/core/handler.go:122 +0xa5
FAIL	github.com/clearmatics/autonity/consensus/test	133.068s
FAIL
```

Logs attached
[TestTendermintStartStopFPlusOneNodes_index_out_of_range.txt](https://github.com/clearmatics/autonity/files/5061707/TestTendermintStartStopFPlusOneNodes_index_out_of_range.txt)

# Acceptance Criteria

Since this happens intermittently, it will be hard to verify the fix therefore the PR should make it clear what the problem was and how it has been fixed.

**Comment by Jason-Zhangxin-Chen** [comment]
To be closed by https://github.com/clearmatics/autonity/pull/689
